name: 'publiccode-softwareversion-check-action'
description: 'This action checks whether softwareVersion in your publiccode.yml file is aligned with the latest tag and is ready to work in conjunction with peter-evans/create-pull-request action to update softwareVersion using a pull request.'
author: 'italia'

inputs:
  publiccode:
    description: 'publiccode.yml path'
    required: false
    default: 'publiccode.yml'
  gitname:
    description: 'Git name configuration for bump commit'
    required: false
    default: 'Publiccode bot'
  gitmail:
    description: 'Git mail configuration for bump commit'
    required: false
    default: ''

outputs:
  version:
    description: 'New version of softwareVersion in publiccode.yml'

runs:
  using: 'node12'
  main: 'dist/index.js'

branding:
  icon: 'activity'
  color: 'white'
