name: 'publiccode-softwareversion-check-action'
description: 'JavaScript GitHub action to check publiccode.yml softwareVersion and releaseDate automatically.'
author: 'italia'

inputs:
  publiccode:
    description: 'publiccode.yml path'
    required: false
    default: 'publiccode.yml'
  gitname:
    description: 'Git name configuration for bump commit'
    required: false
    default: 'Publiccode bot'
  gitmail:
    description: 'Git mail configuration for bump commit'
    required: false
    default: ''

outputs:
  version:
    description: 'New version of softwareVersion field in publiccode.yml'
  releaseDate:
    description: 'New release date of releaseDate field in publiccode.yml'

runs:
  using: 'node12'
  main: 'dist/index.js'

branding:
  icon: 'file'
  color: 'blue'
