name: Test
on:
  push:
    branches:
      - master
  pull_request:
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - uses: italia/publiccode-parser-action@v0.0.2-alpha
        with:
          publiccode: 'data/publiccode.yml'
      - name: Parse publiccode.yml
        uses: ./
        id: pva
        with:
          publiccode: 'data/publiccode.yml'
      - name: Test without tags
        run: |
          test "" = "${{ steps.pva.outputs.version }}"
      - name: Tag your code
        run: |
          git config --global user.email "you@example.com"
          git config --global user.name "Your Name"
          git tag -a v0.3.2 -m "v0.3.2" 
      - name: Parse publiccode.yml with wrong version
        uses: ./
        continue-on-error: true
        id: pvasecond
        with:
          publiccode: 'data/publiccode.yml'
      - name: Test that version has been committed
        run: |
          test "v0.3.2" = "${{ steps.pvasecond.outputs.version }}"
          test "softwareVersion: v0.3.2" = "$(cat data/publiccode.yml | grep -Eo 'softwareVersion:(.*)')"
